import { ProfessionalExperience } from '@/types';

export async function getProfessionalExperience() {
    const exp: ProfessionalExperience[] = [
        {
            role: "Market Insights Analytics",
            company: "International Air Transport Assocation (IATA)",
            logo: "iata_logo.png",
            diagram1: "iata_diagram1.png",
            diagram2: "iata_diagram2.png",
            skills: "Market Research ⋅ Trend Analysis ⋅ Data Storytelling",
            year: "2023",
            summary_title: "Summary",
            summary_paragraph: "At IATA, I worked on the market insights team, focusing on market research and strategy for the Commercial Products & Services group. My responsibilities included defining success metrics, uncovering insights, and aligning them with strategic goals.",
            background_title: "",
            background_subtitle: "",
            background_paragraph: "",
            about_title: "",
            about_paragraph: "",
            project_title: "Key Project",
            project_summary: "I led a project to improve our strategic partnership program, aiming to boost growth and engagement for key stakeholders in the aviation industry.",
            project_subheading1: "Deep Dive into User Research",
            project_desc1: "We began with user research to identify pain points and concerns regarding information sharing and exchange in the industry. We benchmarked our strategic partner benefits and engagement against industry standards and thoroughly evaluated the current partnership strategy.",
            project_subheading2: "Data-Driven Insights",
            project_desc2: "I explored how to offer opportunities and stronger value for money for stakeholders, diving into in-depth analytics and applying a regression model to dissect the key drivers influencing satisfaction, and how these elements interplayed.",
            project_subheading3: "Influencing Strategy with Data",
            project_desc3: "The project ended with a session with IATA's key decision-makers, where we discussed a comprehensive guideline for enhancing the strategic partnership program based on an in-depth analysis of current and potential future use cases."
        },
        {
            role: "Business Analytics - Global Innovation",
            company: "General Motors",
            logo: "gm_logo.png",
            diagram1: "gm_diagram1.png",
            diagram2: "gm_diagram2.png",
            skills: "Go-to-Market Strategy ⋅ Project Management",
            year: "2022",
            summary_title: "Summary",
            summary_paragraph: "At GM's Global Innovation group, I conducted due diligence on V2X data distribution providers, defined the scope of connected vehicle data features, and supported the launch of a cloud-based road safety solution.",
            background_title: "",
            background_subtitle: "",
            background_paragraph: "",
            about_title: "",
            about_paragraph: "",
            project_title: "Key Project",
            project_summary: "",
            project_subheading1: "Launch of Safety View Software",
            project_desc1: "I worked on launching Safety View, a SaaS-Based Road Safety Solution, in partnership with INRIX. This software aimed to support safe street initiatives across the U.S. My main responsibility was to define and communicate the technical requirements of this application to stakeholders, including system specifications and use case walkthroughs before the product launch.",
            project_subheading2: "Partnership Strategy",
            project_desc2: "In the final stages leading up to the launch of Safety View, securing U.S DoT SS4A contracts was a key objective, resulting in over $3.5 million in awards. This was a joint effort with the business development team, focusing on navigating the procurement process and refining the product's whitepaper. Our partnership with INRIX helped enhance the accuracy and efficacy of the Safety View software, positioning GM's technology competitively in the road safety solutions market.",
            project_subheading3: "",
            project_desc3: ""
        },
        {
            role: "Software Engineering",
            company: "Bird&Be",
            logo: "bird&be_logo.png",
            diagram1: "bird&be_diagram1.png",
            diagram2: "bird&be_diagram2.png",
            skills: "Full-Stack Development ⋅ Data Migration",
            year: "2021",
            summary_title: "Summary",
            summary_paragraph: "I worked on an agile team of engineers, handling both front-end development and back-end logic, managing synchronization for e-commerce orders, and API integrations.",
            background_title: "",
            background_subtitle: "",
            background_paragraph: "",
            about_title: "",
            about_paragraph: "",
            project_title: "Key Project",
            project_summary: "A significant project at Bird&Be was developing tools for our customer support team to search, update, and delete orders internally. Transitioning our data from BigCommerce to Shopify highlighted the need for effective server-side synchronization to manage data across both platforms.",
            project_subheading1: "Tech Stack",
            project_desc1: "Node.js ⋅ Next.js ⋅ TypeScript ⋅ React.js ⋅ PostgreSQL ⋅ Docker ⋅ Auth0 ⋅ Shopify Developer Platform.",
            project_subheading2: "",
            project_desc2: "",
            project_subheading3: "",
            project_desc3: ""
        },
        {
            role: "Software Development & Co-Founding",
            company: "PhaseRx",
            logo: "phaserx_logo.png",
            diagram1: "phaserx_demo.gif",
            diagram2: "",
            skills: "what not to do from concept to launch",
            year: "2021",
            summary_title: "Summary",
            summary_paragraph: "I co-founded and developed an e-prescription dropbox platform for the Canadian healthcare industry.",
            background_title: "",
            background_subtitle: "The Vision of PhaseRx",
            background_paragraph: "We aimed to improve the Canadian healthcare system by using cloud computing to create efficient protocols for e-prescriptions. Our goal was to enhance communication between healthcare providers and pharmacists, reducing administrative tasks and allowing professionals to focus more on patient care.",
            about_title: "",
            about_paragraph: "",
            project_title: "The Startup Experience",
            project_summary: "Co-founding PhaseRx involved building and scaling an application from scratch. I worked closely with product managers and healthcare professionals, developing user interview methodologies, customer journey maps, and user stories, which we then turned into product features. This collaborative process helped us propose MVP and secondary features, create a proof of concept, rapidly prototype, and refine our product through continuous client feedback. A key part of this journey was developing a go-to-market strategy with the help of accelerator programs to ensure our solution met the needs of the healthcare industry.",
            project_subheading1: "",
            project_desc1: "",
            project_subheading2: "",
            project_desc2: "",
            project_subheading3: "",
            project_desc3: ""
        }
    ];

    return exp;
}